comment: off

# measuring code coverage of github and gitlab is not viable
ignore:
  - "pkg/github"
  - "pkg/gitlab"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1.5%
        removed_code_behavior: adjust_base

